# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family      VictorMono Nerd Font Semibold
italic_font      VictorMono Nerd Font Semibold Italic
bold_font        VictorMono Nerd Font Bold
bold_italic_font VictorMono Nerd Font Bold Italic
font_size 12.0

enable_audio_bell no
background_opacity 1
background_image $HOME/.config/kitty/waifu_laptop.png
background_image_layout scaled
background_image_linear no
map ctrl+shift+t launch --cwd=current --type=tab
open_url_with default
url_prefixes http https file ftp gemini irc gopher mailto news git
detect_urls yes

# layout
map F5 launch --cwd=current --location=hsplit
map F6 launch --cwd=current --location=vsplit
map F7 layout_action rotate
enabled_layouts horizontal
enabled_layouts vertical
enabled_layouts splits:split_axis=horizontal
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
initial_window_width 1920
initial_window_height 1080
draw_minimal_borders yes


# tweaks
input_delay 3
sync_to_monitor yes

# start a workflow !!!
# startup_session ./sessions/go_dev.conf
#
# theme
include ./kitty-themes/themes/AtomOneLight.conf
