font:
  normal:
    family: "Fira Code Nerd Font"
    style: Regular
  bold:
    family: "Fira Code Nerd Font"
  italic:
    family: "Fira Code Nerd Font"
  size: 14

colors:
  primary:
    foreground: '#2B3C2B'
    background: '#C8E3C8'
  cursor:
    text: '#C8E3C8'
    cursor: '#524f67'
  vi_mode_cursor:
    text: '#C8E3C8'
    cursor: '#524f67'
  search:
    matches:
      foreground: '#A3B8A3'
      background: '#D7E8D7'
    focused_match:
      foreground: '#191724'
      background: '#ebbcba'
  hints:
    start:
      foreground: '#908caa'
      background: '#1f1d2e'
    end:
      foreground: '#6e6a86'
      background: '#1f1d2e'
  line_indicator:
    foreground: 'None'
    background: 'None'
  footer_bar:
    foreground: '#2B3C2B'
    background: '#1f1d2e'
  selection:
    text: '#C8E3C8'
    background: '#403d52'
  normal:
    black: '#26233a'
    red: '#D48A8A'
    green: '#4CAF50'
    yellow: '#D4C054'
    blue: '#6F9BC4'
    magenta: '#A47DAB'
    cyan: '#ebbcba'
    white: '#C8E3C8'
  bright:
    black: '#6e6a86'
    red: '#D48A8A'
    green: '#4CAF50'
    yellow: '#D4C054'
    blue: '#6F9BC4'
    magenta: '#A47DAB'
    cyan: '#ebbcba'
    white: '#C8E3C8'
  dim:
    black: '#6e6a86'
    red: '#D48A8A'
    green: '#31748f'
    yellow: '#D4C054'
    blue: '#9ccfd8'
    magenta: '#c4a7e7'
    cyan: '#ebbcba'
    white: '#C8E3C8'
live_config_reload: true
