[font]
  size = 14
  [font.normal]
    family = "FiraCode Nerd Font"
    style = "Regular"
  [font.bold]
    family = "FiraCode Nerd Font"
  [font.italic]
    family = "FiraCode Nerd Font"

# Alacritty configuration file

# Colors
[colors]
  # Default colors
  [colors.primary]
    background = '#C8E3C8' # Background color
    foreground = '#3E3E3E' # Foreground color (text)

  # Cursor colors
  [colors.cursor]
    cursor = '#3E3E3E'       # Cursor color

  # Normal colors
  [colors.normal]
    black = '#3E3E3E'
    red = '#D74D3E'
    green = '#5C8F5C'
    yellow = '#D7C64E'
    blue = '#6F4C93'
    magenta = '#A65E9E'
    cyan = '#4D9FC5'
    white = '#E5E5E5'

  # Bright colors
  [colors.bright]
    black = '#A0A0A0'
    red = '#FF5D5D'
    green = '#77FF77'
    yellow = '#FFFF6D'
    blue = '#6F77FF'
    magenta = '#DCA5E5'
    cyan = '#7DDBDB'
    white = '#FFFFFF'

# Window settings
[window]
  [window.padding]
    x = 10
    y = 10

[env]
  TERM = "xterm-256color"
