[font]
  size = 24
  [font.normal]
    family = "IosevkaTerm Nerd Font"
    style = "Regular"
  [font.bold]
    family = "IosevkaTerm Nerd Font"
    style = "Bold"
  [font.italic]
    family = "IosevkaTerm Nerd Font"
    style = "Italic"

# Alacritty configuration file

# Colors
[colors]
  # Default colors
  [colors.primary]
    background = '#C8E3C8' # Background color
    foreground = '#3E3E3E' # Foreground color (text)

  # Cursor colors
  [colors.cursor]
    cursor = '#3E3E3E'       # Cursor color

  # Normal colors
  [colors.normal]
    black = '#3E3E3E'
    red = '#D74D3E'
    green = '#5C8F5C'
    yellow = '#D7C64E'
    blue = '#6F4C93'
    magenta = '#A65E9E'
    cyan = '#4D9FC5'
    white = '#4B8A4B'  # Dark greenish color for better visibility

  # Bright colors
  [colors.bright]
    black = '#A0A0A0'
    red = '#FF4A4A'    # Darker red for better visibility
    green = '#66CC66'   # Softer green for better visibility
    yellow = '#C6C24E'  # Darker yellow for better visibility
    blue = '#5A67D8'    # Softer blue for better visibility
    magenta = '#DFA5E5' # Softer magenta for better visibility
    cyan = '#6DD5D5'    # Softer cyan for better visibility
    white = '#B0C5B0'   # Lighter greenish gray for better visibility

# Window settings
[window]
  [window.padding]
    x = 10
    y = 10

[env]
  TERM = "xterm-256color"
