ZSH_THEME="lambda"
plugins=(git)

source $HOME/.export
[ -f $HOME/work/.export ] && source $HOME/work/.export

source $ZSH/oh-my-zsh.sh

# Set up fzf key bindings and fuzzy completion
if command -v fzf >/dev/null; then
    source <(fzf --zsh)
fi

source $HOME/.alias

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

eval "$(tmuxifier init -)"
