function ttmux {
  if (pgrep tmux); then
    tmux attach
  else 
    tmux
  fi
  builtin exit
}

function exit {
  if [ ${TMUX} ]; then
      tmux detach
  else 
      builtin exit
  fi
}

ZSH_THEME="lambda"
plugins=(git)

source $HOME/.alias
source $HOME/.export

source $ZSH/oh-my-zsh.sh
[ -f $HOME/.fzf.zsh ] && $HOME/.fzf.zsh

# Start ttmux if not already inside a tmux session
if [ -z "$TMUX" ]; then
    exec ttmux
fi

